### ISSUE TITLE
Current DSv2 files cause error

### ISSUE THREAD

**Issue by matmaxgeds** [kndm/iati-diff#24]
This file causes an error:
[test-datastore.iatistandard.org DSv2 test 2.txt](https://github.com/kndm/iati-diff/files/3529070/test-datastore.iatistandard.org.DSv2.test.2.txt)

matt@Birch:~/$ python3 iati-diff.py test-datastore.iatistandard.org\ DSv2\ test\ 2.txt 
NEW F IS:  </iati-activity>
Traceback (most recent call last):
  File "iati-diff.py", line 141, in <module>
    main()
  File "iati-diff.py", line 104, in main
    result = diffile.diff_files(path_activities + 'formatted-' + output_identifier.text + '.xml', path_datastore + 'formatted-' + output_identifier.text + '.xml', formatter=formatter, diff_options={'F': 1, 'ratio_mode':'accurate'})
  File "/home/matt/.local/lib/python3.7/site-packages/xmldiff/main.py", line 51, in diff_files
    diff_options=diff_options, formatter=formatter)
  File "/home/matt/.local/lib/python3.7/site-packages/xmldiff/main.py", line 37, in _diff
    right_tree = parse_method(right, parser)
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "./datastore/formatted-GB-1-104714.xml", line 1
lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 1, column 2

**Comment by matmaxgeds** [comment]
Example query to get file: https://test-datastore.iatistandard.org/api/activities/?recipient_country=SO&fields=all&page_size=5

**Comment by matmaxgeds** [comment]
@kndm did the last push fix this, if so, please test to confirm and then close
