### ISSUE TITLE
Error Thurs 18th

### ISSUE THREAD

**Issue by matmaxgeds** [kndm/iati-diff#7]
matt@Birch:~/Cloud/Syncthing/Laptop/Downloads/IATIdiff/iati-diff-master$ python3 iati-diff.py activity-list\(2\).xml
iati-diff.py:36: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if new_data:
Traceback (most recent call last):
  File "iati-diff.py", line 58, in <module>
    for line in main.diff_files('./datastore/' + filename + '.xml' , './activities/' + filename + '.xml', formatter=formatter):
  File "/home/matt/.local/lib/python3.7/site-packages/xmldiff/main.py", line 51, in diff_files
    diff_options=diff_options, formatter=formatter)
  File "/home/matt/.local/lib/python3.7/site-packages/xmldiff/main.py", line 37, in _diff
    right_tree = parse_method(right, parser)
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
OSError: Error reading file './activities/.gitignore.xml': failed to load external entity "./activities/.gitignore.xml"

**Comment by kndm** [comment]
@matmaxgeds Should be solved now (tested it on my end), gitignore files were added after the process was working so they had to be taken out of the file element list.
